# Generated by Django 6.1.1 on 2026-09-15 12:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0002_order_cancelled_at_order_shipped_at_order_staff_note_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gateway', models.CharField(max_length=50, verbose_name='درگاه')),
                ('amount', models.DecimalField(decimal_places=0, max_digits=15, verbose_name='مبلغ (تومان)')),
                ('status', models.CharField(choices=[('initiated', 'در انتظار پرداخت'), ('succeeded', 'موفق'), ('failed', 'ناموفق')], db_index=True, default='initiated', max_length=20, verbose_name='وضعیت')),
                ('authority', models.CharField(blank=True, db_index=True, max_length=100, verbose_name='شناسه درخواست')),
                ('reference_id', models.CharField(blank=True, max_length=100, verbose_name='شماره پیگیری پرداخت')),
                ('card_pan', models.CharField(blank=True, max_length=32, verbose_name='شماره کارت (ماسک\u200cشده)')),
                ('raw_response', models.JSONField(blank=True, default=dict, verbose_name='پاسخ درگاه')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('verified_at', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ تایید')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='orders.order', verbose_name='سفارش')),
            ],
            options={
                'verbose_name': 'پرداخت',
                'verbose_name_plural': 'پرداخت\u200cها',
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('authority', ''), _negated=True), fields=('gateway', 'authority'), name='unique_gateway_authority')],
            },
        ),
    ]
