# Generated by Django 6.1.1 on 2026-09-14 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HeroBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان')),
                ('subtitle', models.CharField(blank=True, max_length=300, verbose_name='زیرعنوان')),
                ('background_image', models.ImageField(upload_to='banners/', verbose_name='تصویر پس\u200cزمینه')),
                ('primary_cta_label', models.CharField(blank=True, max_length=50, verbose_name='متن دکمه اول')),
                ('primary_cta_url', models.CharField(blank=True, max_length=500, verbose_name='لینک دکمه اول')),
                ('secondary_cta_label', models.CharField(blank=True, max_length=50, verbose_name='متن دکمه دوم')),
                ('secondary_cta_url', models.CharField(blank=True, max_length=500, verbose_name='لینک دکمه دوم')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('position', models.PositiveSmallIntegerField(default=0, verbose_name='ترتیب')),
            ],
            options={
                'verbose_name': 'بنر صفحه اصلی',
                'verbose_name_plural': 'بنرهای صفحه اصلی',
                'ordering': ['position', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان')),
                ('slug', models.SlugField(allow_unicode=True, max_length=200, unique=True, verbose_name='نامک')),
                ('body', models.TextField(verbose_name='متن')),
                ('is_published', models.BooleanField(default=True, verbose_name='منتشر شده')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین ویرایش')),
            ],
            options={
                'verbose_name': 'صفحه',
                'verbose_name_plural': 'صفحات',
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(default='09391098198', max_length=20, verbose_name='موبایل')),
                ('bale_username', models.CharField(blank=True, default='Sportyadaki', max_length=100, verbose_name='نام کاربری بله')),
                ('eitaa_username', models.CharField(blank=True, default='sportyadaki', max_length=100, verbose_name='نام کاربری ایتا')),
            ],
            options={
                'verbose_name': 'تنظیمات سایت',
                'verbose_name_plural': 'تنظیمات سایت',
            },
        ),
    ]
