# Generated by Django 6.1.1 on 2026-09-15 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='herobanner',
            name='placement',
            field=models.CharField(choices=[('top', 'بالای صفحه اصلی'), ('middle', 'وسط صفحه اصلی')], default='top', max_length=10, verbose_name='جایگاه'),
        ),
    ]
