# Generated by Django 6.1.1 on 2026-09-15 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_herobanner_placement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='herobanner',
            name='background_image',
            field=models.ImageField(blank=True, upload_to='banners/', verbose_name='تصویر پس\u200cزمینه'),
        ),
    ]
