# Generated by Django 6.1.1 on 2026-09-15 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_herobanner_background_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='herobanner',
            name='content_side',
            field=models.CharField(choices=[('right', 'راست'), ('left', 'چپ')], default='right', help_text='متن و دکمه\u200cها روی این طرف بنر قرار می\u200cگیرند؛ طرف خالی تصویر را انتخاب کنید.', max_length=5, verbose_name='جای متن'),
        ),
    ]
