# Generated by Django 6.1.1 on 2026-09-15 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_herobanner_content_side'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='logo',
            field=models.ImageField(blank=True, help_text='PNG با پس\u200cزمینه واقعاً شفاف یا سفید (نه طرح شطرنجی)، حداقل ۱۲۰ پیکسل ارتفاع.', upload_to='site/', verbose_name='لوگو'),
        ),
    ]
