# Generated by Django 6.1.1 on 2026-09-15 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_sitesettings_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='free_shipping_min_amount',
            field=models.DecimalField(blank=True, decimal_places=0, help_text='اگر جمع کالاها به این مبلغ برسد، ارسال رایگان است. خالی یعنی غیرفعال.', max_digits=15, null=True, verbose_name='ارسال رایگان از مبلغ سفارش (تومان)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='free_shipping_min_items',
            field=models.PositiveIntegerField(blank=True, help_text='اگر تعداد کالاهای سبد به این عدد برسد، ارسال رایگان است. خالی یعنی غیرفعال.', null=True, verbose_name='ارسال رایگان از تعداد کالا'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='shipping_cost',
            field=models.DecimalField(decimal_places=0, default=0, help_text='مبلغ ثابت ارسال که برای همه سفارش\u200cها یکسان است.', max_digits=12, verbose_name='هزینه ارسال (تومان)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='tax_rate',
            field=models.DecimalField(decimal_places=2, default=0, help_text='روی جمع کالاها محاسبه و به مبلغ سفارش اضافه می\u200cشود. ۰ یعنی بدون مالیات.', max_digits=5, verbose_name='نرخ مالیات (درصد)'),
        ),
    ]
