# Generated by Django 6.1.1 on 2026-09-15 15:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_sitesettings_free_shipping_min_amount_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeroBannerImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='banners/', verbose_name='تصویر')),
                ('position', models.PositiveSmallIntegerField(default=0, verbose_name='ترتیب')),
                ('banner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extra_images', to='core.herobanner', verbose_name='بنر')),
            ],
            options={
                'verbose_name': 'تصویر اسلایدشو بنر',
                'verbose_name_plural': 'تصاویر اسلایدشو بنر',
                'ordering': ['position', 'pk'],
            },
        ),
    ]
