# Generated by Django 6.1.1 on 2026-09-17 12:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_product_rating'),
        ('core', '0007_herobannerimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='CheckoutSuggestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('position', models.PositiveSmallIntegerField(default=0, verbose_name='ترتیب')),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='checkout_suggestion', to='catalog.product', verbose_name='محصول')),
            ],
            options={
                'verbose_name': 'پیشنهاد تکمیل خرید',
                'verbose_name_plural': 'پیشنهادهای تکمیل خرید',
                'ordering': ['position', 'pk'],
            },
        ),
    ]
