# Generated by Django 6.1.1 on 2026-09-14 11:16

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BodyStyle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='نام')),
                ('slug', models.SlugField(allow_unicode=True, max_length=200, unique=True, verbose_name='نامک')),
                ('wp_term_id', models.PositiveBigIntegerField(blank=True, editable=False, null=True, unique=True)),
            ],
            options={
                'verbose_name': 'نوع بدنه',
                'verbose_name_plural': 'انواع بدنه',
                'ordering': ['name'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CarBrand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='نام')),
                ('slug', models.SlugField(allow_unicode=True, max_length=200, unique=True, verbose_name='نامک')),
                ('wp_term_id', models.PositiveBigIntegerField(blank=True, editable=False, null=True, unique=True)),
                ('image', models.ImageField(blank=True, upload_to='car-brands/', verbose_name='لوگو')),
            ],
            options={
                'verbose_name': 'برند خودرو',
                'verbose_name_plural': 'برندهای خودرو',
                'ordering': ['name'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='نام')),
                ('slug', models.SlugField(allow_unicode=True, max_length=200, unique=True, verbose_name='نامک')),
                ('wp_term_id', models.PositiveBigIntegerField(blank=True, editable=False, null=True, unique=True)),
            ],
            options={
                'verbose_name': 'رنگ',
                'verbose_name_plural': 'رنگ\u200cها',
                'ordering': ['name'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Make',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='نام')),
                ('slug', models.SlugField(allow_unicode=True, max_length=200, unique=True, verbose_name='نامک')),
                ('wp_term_id', models.PositiveBigIntegerField(blank=True, editable=False, null=True, unique=True)),
            ],
            options={
                'verbose_name': 'سازنده',
                'verbose_name_plural': 'سازنده\u200cها',
                'ordering': ['name'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ManufactureYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='نام')),
                ('slug', models.SlugField(allow_unicode=True, max_length=200, unique=True, verbose_name='نامک')),
                ('wp_term_id', models.PositiveBigIntegerField(blank=True, editable=False, null=True, unique=True)),
            ],
            options={
                'verbose_name': 'سال ساخت',
                'verbose_name_plural': 'سال\u200cهای ساخت',
                'ordering': ['name'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PartBrand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='نام')),
                ('slug', models.SlugField(allow_unicode=True, max_length=200, unique=True, verbose_name='نامک')),
                ('wp_term_id', models.PositiveBigIntegerField(blank=True, editable=False, null=True, unique=True)),
                ('image', models.ImageField(blank=True, upload_to='part-brands/', verbose_name='لوگو')),
            ],
            options={
                'verbose_name': 'برند قطعه',
                'verbose_name_plural': 'برندهای قطعه',
                'ordering': ['name'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CarModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='نام')),
                ('slug', models.SlugField(allow_unicode=True, max_length=200, unique=True, verbose_name='نامک')),
                ('wp_term_id', models.PositiveBigIntegerField(blank=True, editable=False, null=True, unique=True)),
                ('image', models.ImageField(blank=True, upload_to='car-models/', verbose_name='عکس مدل خودرو')),
                ('brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='car_models', to='catalog.carbrand', verbose_name='برند خودرو')),
            ],
            options={
                'verbose_name': 'مدل خودرو',
                'verbose_name_plural': 'مدل\u200cهای خودرو',
                'ordering': ['name'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='نام')),
                ('slug', models.SlugField(allow_unicode=True, max_length=200, unique=True, verbose_name='نامک')),
                ('wp_term_id', models.PositiveBigIntegerField(blank=True, editable=False, null=True, unique=True)),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
                ('image', models.ImageField(blank=True, upload_to='categories/', verbose_name='تصویر')),
                ('role', models.CharField(blank=True, choices=[('', 'معمولی'), ('sport', 'لوازم اسپرت'), ('accessory', 'اکسسوری')], default='', max_length=20, verbose_name='نقش ویژه')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='catalog.productcategory', verbose_name='دسته والد')),
            ],
            options={
                'verbose_name': 'دسته\u200cبندی محصول',
                'verbose_name_plural': 'دسته\u200cبندی\u200cهای محصول',
                'ordering': ['name'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='نام')),
                ('slug', models.SlugField(allow_unicode=True, max_length=255, unique=True, verbose_name='نامک')),
                ('status', models.CharField(choices=[('draft', 'پیش\u200cنویس'), ('publish', 'منتشر شده'), ('private', 'خصوصی')], db_index=True, default='draft', max_length=20, verbose_name='وضعیت')),
                ('short_description', models.TextField(blank=True, verbose_name='توضیح کوتاه')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
                ('image', models.ImageField(blank=True, upload_to='products/%Y/%m/', verbose_name='تصویر شاخص')),
                ('sku', models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='شناسه (SKU)')),
                ('global_unique_id', models.CharField(blank=True, max_length=100, verbose_name='GTIN / UPC / EAN / ISBN')),
                ('regular_price', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='قیمت')),
                ('sale_price', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='قیمت فروش ویژه')),
                ('sale_starts_at', models.DateTimeField(blank=True, null=True, verbose_name='شروع فروش ویژه')),
                ('sale_ends_at', models.DateTimeField(blank=True, null=True, verbose_name='پایان فروش ویژه')),
                ('is_virtual', models.BooleanField(default=False, verbose_name='مجازی')),
                ('is_downloadable', models.BooleanField(default=False, verbose_name='دانلودی')),
                ('manage_stock', models.BooleanField(default=False, verbose_name='مدیریت موجودی')),
                ('stock_quantity', models.IntegerField(blank=True, null=True, verbose_name='تعداد موجودی')),
                ('stock_status', models.CharField(choices=[('instock', 'موجود'), ('outofstock', 'ناموجود'), ('onbackorder', 'پیش\u200cسفارش')], db_index=True, default='instock', max_length=20, verbose_name='وضعیت موجودی')),
                ('tax_status', models.CharField(choices=[('taxable', 'مشمول مالیات'), ('shipping', 'فقط هزینه ارسال'), ('none', 'بدون مالیات')], default='taxable', max_length=20, verbose_name='وضعیت مالیات')),
                ('tax_class', models.CharField(blank=True, max_length=100, verbose_name='کلاس مالیاتی')),
                ('total_sales', models.PositiveIntegerField(default=0, verbose_name='تعداد فروش')),
                ('rating_count', models.PositiveIntegerField(default=0, verbose_name='تعداد امتیازها')),
                ('average_rating', models.DecimalField(decimal_places=2, default=0, max_digits=3, verbose_name='میانگین امتیاز')),
                ('wp_post_id', models.PositiveBigIntegerField(blank=True, editable=False, null=True, unique=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین ویرایش')),
                ('body_styles', models.ManyToManyField(blank=True, related_name='products', to='catalog.bodystyle', verbose_name='انواع بدنه')),
                ('car_models', models.ManyToManyField(blank=True, related_name='products', to='catalog.carmodel', verbose_name='مدل\u200cهای خودرو')),
                ('colors', models.ManyToManyField(blank=True, related_name='products', to='catalog.color', verbose_name='رنگ\u200cها')),
                ('makes', models.ManyToManyField(blank=True, related_name='products', to='catalog.make', verbose_name='سازنده\u200cها')),
                ('part_brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='catalog.partbrand', verbose_name='برند قطعه')),
                ('years', models.ManyToManyField(blank=True, related_name='products', to='catalog.manufactureyear', verbose_name='سال\u200cهای ساخت')),
                ('categories', models.ManyToManyField(blank=True, related_name='products', to='catalog.productcategory', verbose_name='دسته\u200cبندی\u200cها')),
            ],
            options={
                'verbose_name': 'محصول',
                'verbose_name_plural': 'محصولات',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='products/%Y/%m/', verbose_name='تصویر')),
                ('alt', models.CharField(blank=True, max_length=255, verbose_name='متن جایگزین')),
                ('position', models.PositiveSmallIntegerField(default=0, verbose_name='ترتیب')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery', to='catalog.product', verbose_name='محصول')),
            ],
            options={
                'verbose_name': 'تصویر گالری',
                'verbose_name_plural': 'گالری تصاویر',
                'ordering': ['position', 'pk'],
            },
        ),
        migrations.AddConstraint(
            model_name='productcategory',
            constraint=models.UniqueConstraint(condition=models.Q(('role', ''), _negated=True), fields=('role',), name='unique_category_role'),
        ),
    ]
