# Generated by Django 6.1.1 on 2026-09-15 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='carbrand',
            options={'ordering': ['position', 'name'], 'verbose_name': 'برند خودرو', 'verbose_name_plural': 'برندهای خودرو'},
        ),
        migrations.AddField(
            model_name='carbrand',
            name='position',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='ترتیب نمایش'),
        ),
    ]
