# Generated by Django 6.1.1 on 2026-09-15 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_alter_carbrand_options_carbrand_position'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='productcategory',
            name='unique_category_role',
        ),
        migrations.AddField(
            model_name='product',
            name='accessory',
            field=models.BooleanField(default=False, verbose_name='لوازم جانبی'),
        ),
        migrations.AddField(
            model_name='product',
            name='sport',
            field=models.BooleanField(default=False, verbose_name='لوازم اسپرت'),
        ),
        migrations.RemoveField(
            model_name='productcategory',
            name='role',
        ),
    ]
