# Generated by Django 6.1.1 on 2026-09-14 11:16

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'در انتظار پرداخت'), ('processing', 'در حال انجام'), ('on-hold', 'در انتظار بررسی'), ('completed', 'تکمیل شده'), ('cancelled', 'لغو شده'), ('refunded', 'مسترد شده'), ('failed', 'ناموفق'), ('checkout-draft', 'پیش\u200cنویس')], db_index=True, default='pending', max_length=20, verbose_name='وضعیت')),
                ('currency', models.CharField(default='IRT', max_length=10, verbose_name='واحد پول')),
                ('billing_email', models.EmailField(blank=True, max_length=254, verbose_name='ایمیل')),
                ('customer_note', models.TextField(blank=True, verbose_name='یادداشت مشتری')),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='مبلغ کل')),
                ('tax_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='مالیات')),
                ('shipping_total', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='هزینه ارسال')),
                ('shipping_tax', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='مالیات ارسال')),
                ('discount_total', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='تخفیف')),
                ('discount_tax', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='مالیات تخفیف')),
                ('payment_method', models.CharField(blank=True, max_length=100, verbose_name='روش پرداخت')),
                ('payment_method_title', models.CharField(blank=True, max_length=200, verbose_name='عنوان روش پرداخت')),
                ('transaction_id', models.CharField(blank=True, max_length=100, verbose_name='شناسه تراکنش')),
                ('carrier', models.CharField(blank=True, choices=[('tipax', 'تیپاکس'), ('post', 'پست ایران')], max_length=20, verbose_name='شرکت حمل')),
                ('tracking_code', models.CharField(blank=True, max_length=100, verbose_name='کد رهگیری')),
                ('created_via', models.CharField(blank=True, max_length=100, verbose_name='ایجاد از طریق')),
                ('order_key', models.CharField(blank=True, max_length=100, verbose_name='کلید سفارش')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP مشتری')),
                ('user_agent', models.TextField(blank=True, verbose_name='مرورگر مشتری')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='تاریخ ثبت')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین ویرایش')),
                ('paid_at', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ پرداخت')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ تکمیل')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to=settings.AUTH_USER_MODEL, verbose_name='مشتری')),
            ],
            options={
                'verbose_name': 'سفارش',
                'verbose_name_plural': 'سفارش\u200cها',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='نام محصول')),
                ('sku', models.CharField(blank=True, max_length=100, verbose_name='شناسه (SKU)')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='تعداد')),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='جمع قبل از تخفیف')),
                ('subtotal_tax', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='مالیات قبل از تخفیف')),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='جمع')),
                ('total_tax', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='مالیات')),
                ('wp_order_item_id', models.PositiveBigIntegerField(blank=True, editable=False, null=True, unique=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.order', verbose_name='سفارش')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_items', to='catalog.product', verbose_name='محصول')),
            ],
            options={
                'verbose_name': 'قلم سفارش',
                'verbose_name_plural': 'اقلام سفارش',
            },
        ),
        migrations.CreateModel(
            name='OrderAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address_type', models.CharField(choices=[('billing', 'صورتحساب'), ('shipping', 'ارسال')], max_length=10, verbose_name='نوع')),
                ('first_name', models.CharField(blank=True, max_length=100, verbose_name='نام')),
                ('last_name', models.CharField(blank=True, max_length=100, verbose_name='نام خانوادگی')),
                ('company', models.CharField(blank=True, max_length=200, verbose_name='شرکت')),
                ('address_1', models.CharField(blank=True, max_length=255, verbose_name='آدرس')),
                ('address_2', models.CharField(blank=True, max_length=255, verbose_name='ادامه آدرس')),
                ('city', models.CharField(blank=True, max_length=100, verbose_name='شهر')),
                ('state', models.CharField(blank=True, max_length=100, verbose_name='استان')),
                ('postcode', models.CharField(blank=True, max_length=20, verbose_name='کد پستی')),
                ('country', models.CharField(default='IR', max_length=2, verbose_name='کشور')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='ایمیل')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='تلفن')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to='orders.order', verbose_name='سفارش')),
            ],
            options={
                'verbose_name': 'آدرس سفارش',
                'verbose_name_plural': 'آدرس\u200cهای سفارش',
                'constraints': [models.UniqueConstraint(fields=('order', 'address_type'), name='unique_order_address_type')],
            },
        ),
    ]
