# Generated by Django 6.1.1 on 2026-09-15 12:07

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='cancelled_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='تاریخ لغو'),
        ),
        migrations.AddField(
            model_name='order',
            name='shipped_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='تاریخ ارسال'),
        ),
        migrations.AddField(
            model_name='order',
            name='staff_note',
            field=models.TextField(blank=True, help_text='فقط برای مدیران نمایش داده می\u200cشود.', verbose_name='یادداشت داخلی'),
        ),
        migrations.AddField(
            model_name='order',
            name='stock_deducted',
            field=models.BooleanField(default=False, editable=False, verbose_name='کسر از موجودی'),
        ),
        migrations.AddField(
            model_name='order',
            name='subtotal_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='جمع کالاها'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='قیمت واحد'),
        ),
        migrations.AlterField(
            model_name='order',
            name='carrier',
            field=models.CharField(blank=True, choices=[('post', 'پست ایران'), ('tipax', 'تیپاکس'), ('courier', 'پیک موتوری')], max_length=20, verbose_name='روش / شرکت ارسال'),
        ),
        migrations.AlterField(
            model_name='order',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='تاریخ تحویل'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'در انتظار پرداخت'), ('paid', 'پرداخت شده'), ('processing', 'در حال آماده\u200cسازی'), ('shipped', 'ارسال شده'), ('delivered', 'تحویل شده'), ('cancelled', 'لغو شده'), ('failed', 'پرداخت ناموفق')], db_index=True, default='pending', max_length=20, verbose_name='وضعیت'),
        ),
        migrations.AlterField(
            model_name='order',
            name='tracking_code',
            field=models.CharField(blank=True, max_length=100, verbose_name='کد رهگیری مرسوله'),
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(editable=False, max_length=30, unique=True, verbose_name='شماره فاکتور')),
                ('issued_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاریخ صدور')),
                ('customer_name', models.CharField(max_length=200, verbose_name='نام خریدار')),
                ('customer_phone', models.CharField(max_length=20, verbose_name='موبایل خریدار')),
                ('billing_address', models.TextField(blank=True, verbose_name='نشانی')),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='جمع کالاها')),
                ('shipping', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='هزینه ارسال')),
                ('discount', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='تخفیف')),
                ('tax_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='نرخ مالیات (درصد)')),
                ('tax', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='مالیات')),
                ('total', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='مبلغ قابل پرداخت')),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='invoice', to='orders.order', verbose_name='سفارش')),
            ],
            options={
                'verbose_name': 'فاکتور',
                'verbose_name_plural': 'فاکتورها',
                'ordering': ['-issued_at'],
            },
        ),
    ]
